### ISSUE TITLE
[BUG] Error message when failing to fetch Load Testing Resource is too broad

### ISSUE THREAD

**Issue by tonybaloney** [Azure/load-testing#41]
The code to get the Load Testing Resource will raise an error if the Azure API returns anything other than HTTP 200 to say that the resource does not exist.

https://github.com/Azure/load-testing/blob/40f4bb10cb50b4510e24da69b544a95675e33393/src/main.ts#L290-L294

I'm getting this error, but the resource does exist.

If the API returns a different error condition, e.g. a permissions error, this action will still report the resource does not exist and the error detail is not captured anywhere to understand why it isn't working

**Comment by ninallam** [comment]
@radhikajain99 Can you please look into this?
