### ISSUE TITLE
[BUG] Azure Load Testing Cannot create a new test via pipeline 

### ISSUE THREAD

**Issue by ht1994G** [Azure/load-testing#56]
**Describe the bug**
While creating a new load test via pipeline, by using 
```
version: v0.1
testId: SampleTest
displayName: Sample Test
testPlan: SampleTest.jmx
description: Load test website home page 
...
```
if the `testId` does not exist, it should create a new load test in the Resource Group. Based on what we observed, On Monday, July 26th, the test creation was successful, but since that day, the pipeline would fail if the test does not exist and it does not create a new test with a new `testId` and shows this error:
```
error:
`{ error:
   { code: 'TestNotFound',
     message: 'Test couldn\'t find with given identifier NAME',
     target: null,
     details: null } }
##[error]Error in getting the test.`
```

Based on the recent changes on this repo, this message was an added part in recent changes (2 days ago) 
so now as long as the `testId` already exists the pipeline would update the values and run a new test, but it cannot create a new test with a new `testId`

**To Reproduce**
1.  Create a pipeline plan with AzureLoadTest@1 based on this: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-load-test-v1?view=azure-pipelines&viewFallbackFrom=azure-devops 
2. Create a Load Test Config YAML based on this: https://learn.microsoft.com/en-us/azure/load-testing/reference-test-config-yaml
3. in testId section add a non existing test name/id
4. Run the pipeline

**Expected behavior**
The pipeline will fail with error: `Error in getting the test.`

**Screenshots**
![Screenshot 2023-06-28 at 9 54 58 PM](https://github.com/Azure/load-testing/assets/137946349/14229d32-b2bc-4dd4-aba9-91cb76a27425)

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome,]
 - Version [13.4.1 ]

**Smartphone (please complete the following information):** 
NA

**Additional context**
The last time the test creation was successful was July 26th, 2023.
By looking at the repo we found that the error is coming from here probably:
![Screenshot 2023-06-28 at 9 43 54 PM](https://github.com/Azure/load-testing/assets/137946349/f00ea89a-478c-4103-9f5d-efdf568d1064)

**Comment by ninallam** [comment]
@ht1994G The issue if fixed now. Please run and let us know if you are still facing the issue.
