### ISSUE TITLE
[BUG] Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by cmyllis** [Azure/load-testing#79]
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: azure/load-testing@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
This appears after every run via a workflow. Most of the other actions are updated to use Node.js 20 (actions/checkout, azure/login etc).

**Comment by ninallam** [comment]
@cmyllis Thanks for raising the issue. We will work on this and keep you posted.

**Comment by cmyllis** [comment]
https://github.com/Azure/load-testing/pull/80
Not sure if anything else is needed.
