### ISSUE TITLE
[BUG] Tests fail to start with cli issue

### ISSUE THREAD

**Issue by cmyllis** [Azure/load-testing#95]
**Describe the bug**
When triggering the tests from our github actions we started getting this error.
`An error occurred while getting credentials from Azure CLI: Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at execFile (node:child_process:351:17)
    at C:\gh-performancetests\_work\_actions\azure\load-testing\v1.1.23\lib\mappers.js:378:42
    at new Promise (<anonymous>)
    at C:\gh-performancetests\_work\_actions\azure\load-testing\v1.1.23\lib\mappers.js:377:16
    at Generator.next (<anonymous>)
    at C:\gh-performancetests\_work\_actions\azure\load-testing\v1.1.23\lib\mappers.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\gh-performancetests\_work\_actions\azure\load-testing\v1.1.23\lib\mappers.js:27:12)`

**To Reproduce**
Not sure but happens each time for us

**Expected behavior**
For the tests to be triggered.

**Screenshots**
![image](https://github.com/Azure/load-testing/assets/96247992/febc7a95-707c-45f7-ae26-02b32741ad4e)

**Comment by ninallam** [comment]
@cmyllis Thanks for reaching out. We will check the issue and get back.

**Comment by mohitpavan** [comment]
https://github.com/nodejs/node/issues/52554 there is an issue with a nodemodule in windows this is a breaking change, fix will be up by today EOD.

**Comment by mohitpavan** [comment]
the fix is deployed now. please let us know if you stil lface the issue, we were able to repro the issue and fixed and able to see the issue to be fixed too.
closing the issue assuming its fixed for cx too.
